### ISSUE TITLE
LDAP group policies are null

### ISSUE THREAD

**Issue by warroyo** [Caiyeon/goldfish#169]
i am running vault 0.8.3 wiht LDAP configured. I am able to see my ldap groups but the policys column is empty. looking at the json response the value for policies is null.

**Comment by Caiyeon** [comment]
Could you clarify? 
- did the policies column show up but with no policies, or is there column just gone? 
- is this with one LDAP group or all? 
- do any of your LDAP groups have no policies?

**Comment by warroyo** [comment]
the column is there but there are no values in it. this is happening with all ldap groups. all groups also have policies attached to them. 

when looking at the json form `/v1/ldap/groups` in the chrome network tab this is what is returned.

```
{"result":[{"Name":"group1","Policies":null},{"Name":"group2","Policies":null},{"Name":"group3","Policies":null}]}
```

**Comment by gites** [comment]
Same thing for me. Administration->User->LDAP page looks like this:

![LDAP](https://screenshots.firefoxusercontent.com/images/b62938b9-8131-4cba-aa85-60ec6a4b2b0e.png)

Also goldfish is reporting ` invalid memory address or nil pointer dereference` in logs:
```
{"time":"2017-10-09T15:07:10.606421541Z","id":"","remote_ip":"1.1.1.1","host":"vault:443","method":"GET","uri":"/v1/ldap/users","status":500, "latency":8558246,"latency_human":"8.558246ms","bytes_in":0,"bytes_out":35}
{"time":"2017-10-09T15:07:10.620187492Z","id":"","remote_ip":"1.1.1.1","host":"vault:443","method":"GET","uri":"/v1/ldap/groups","status":200, "latency":24889669,"latency_human":"24.889669ms","bytes_in":0,"bytes_out":109}
{"time":"2017-10-09T15:07:18.91499285Z","level":"-","prefix":"echo","file":"asm_amd64.s","line":"510","message":"[\x1b[31mPANIC RECOVER\x1b[0m] runtime error: invalid memory address or nil pointer dereference goroutine 5526 [running]:\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x2322f60, 0x1000, 0xc4207a0000, 0x2f87bc0, 0xc420462460)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/recover.go:75 +0x12a\npanic(0x180ea00, 0x2fcf440)\n\tC:/Go/src/runtime/panic.go:491 +0x283\ngithub.com/caiyeon/goldfish/vault.AuthInfo.ListLDAPUsers(0x1ac90bd, 0x5, 0xc4206f4d50, 0x24, 0x0, 0x0, 0x10, 0x170b560, 0xc420220f01, 0xc420750f60, ...)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vault/ldap.go:73 +0xb3\ngithub.com/caiyeon/goldfish/handlers.GetLDAPUsers.func1(0x2f87bc0, 0xc420462460, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/handlers/ldap.go:40 +0xb8\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).add.func1(0x2f87bc0, 0xc420462460, 0x17, 0x1b2b708)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:467 +0x87\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.SecureWithConfig.func1.1(0x2f87bc0, 0xc420462460, 0xd, 0x1b02faa)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/secure.go:113 +0x2af\nmain.main.func1.1(0x2f87bc0, 0xc420462460, 0xc4204359e0, 0x2f79980)\n\tF:/gopath/src/github.com/caiyeon/goldfish/server.go:135 +0xa4\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.GzipWithConfig.func1.1(0x2f87bc0, 0xc420462460, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/compress.go:92 +0x17f\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.BodyLimitWithConfig.func1.1(0x2f87bc0, 0xc420462460, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/body_limit.go:87 +0x19f\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x2f87bc0, 0xc420462460, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/recover.go:82 +0xe1\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0x2f87bc0, 0xc420462460, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/logger.go:111 +0x121\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x2f87bc0, 0xc420462460, 0xc4202406d8, 0x1aa8da0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:558 +0x108\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc420240680, 0x2f79980, 0xc4205aa168, 0xc4204fed00)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:567 +0x228\nnet/http.serverHandler.ServeHTTP(0xc42006fba0, 0x2f79980, 0xc4205aa168, 0xc4204fed00)\n\tC:/Go/src/net/http/server.go:2619 +0xb4\nnet/http.initNPNRequest.ServeHTTP(0xc420259c00, 0xc42006fba0, 0x2f79980, 0xc4205aa168, 0xc4204fed00)\n\tC:/Go/src/net/http/server.go:3164 +0x9a\nnet/http.(*initNPNRequest).ServeHTTP(0xc4206a0240, 0x2f79980, 0xc4205aa168, 0xc4204fed00)\n\t<autogenerated>:1 +0x63\nnet/http.(Handler).ServeHTTP-fm(0x2f79980, 0xc4205aa168, 0xc4204fed00)\n\tC:/Go/src/net/http/h2_bundle.go:5462 +0x4d\nnet/http.(*http2serverConn).runHandler(0xc420668000, 0xc4205aa168, 0xc4204fed00, 0xc420731420)\n\tC:/Go/src/net/http/h2_bundle.go:5747 +0x89\ncreated by net/http.(*http2serverConn).processHeaders\n\tC:/Go/src/net/http/h2_bundle.go:5481 +0x495\n\ngoroutine 1 [IO wait, 16 minutes]:\ninternal/poll.runtime_pollWait(0x7f6bd3ad5f70, 0x72, 0xffffffffffffffff)\n\tC:/Go/src/runtime/netpoll.go:173 +0x57\ninternal/poll.(*pollDesc).wait(0xc4201f9418, 0x72, 0xc420481700, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xae\ninternal/poll.(*pollDesc).waitRead(0xc4201f9418, 0xffffffffffffff00, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_poll_runtime.go:90 +0x3d\ninternal/poll.(*FD).Accept(0xc4201f9400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_unix.go:334 +0x1e2\nnet.(*netFD).accept(0xc4201f9400, 0x4106e7, 0xc420259c00, 0x3)\n\tC:/Go/src/net/fd_unix.go:238 \n"}
```

maybe this is related: https://github.com/hashicorp/vault/pull/3421

**Comment by Caiyeon** [comment]
Ah yes, that would explain it. I'll see how I can make this work on both 0.8.3 and prior.

**Comment by Caiyeon** [comment]
There's actually 2 bugs here, and they have both been fixed - theoretically.
I can't guarantee a release date, but you are welcome to try out the build artifacts from circle CI.

Thanks the report!
